baseurl = "/"
languageCode = "en-us"
title = "Bistro Ravi"
publishDir = "docs"
[params]
  description = "Ein authentisches indisches Restaurant in Bamberg."

[[menu.main]]
    name = "About"
    url  = "/about"
    weight = 1
[[menu.main]]
    name = "Food"
    url  = "/food"
    weight = 2
[[menu.main]]
    name = "Contact"
    url  = "/contact"
    weight = 3
